/* 谁是卧底 · 家庭海量精选词库 (435+ 组亲子/双语/校园/科技经典词对) */
const UNDERCOVER_WORD_POOLS = {
  // 1. 亲子生活与美食经典 (85 组)
  life_food: {
    name: '🍽️ 亲子生活美食',
    desc: '贴近家庭生活，简单易描述，全家老少上手即玩',
    pairs: [
      { c: '牛奶', u: '豆浆' },
      { c: '饺子', u: '包子' },
      { c: '可乐', u: '雪碧' },
      { c: '苹果', u: '梨' },
      { c: '橘子', u: '橙子' },
      { c: '汉堡', u: '披萨' },
      { c: '烤肉', u: '火锅' },
      { c: '牙刷', u: '马桶刷' },
      { c: '纸巾', u: '湿纸巾' },
      { c: '脸盆', u: '水桶' },
      { c: '枕头', u: '抱枕' },
      { c: '拖把', u: '扫把' },
      { c: '雨伞', u: '雨衣' },
      { c: '眼镜', u: '墨镜' },
      { c: '面条', u: '米线' },
      { c: '方便面', u: '挂面' },
      { c: '煎蛋', u: '荷包蛋' },
      { c: '冰淇淋', u: '冰棍' },
      { c: '饼干', u: '薯片' },
      { c: '蛋糕', u: '面包' },
      { c: '奶茶', u: '咖啡' },
      { c: '番茄酱', u: '辣椒酱' },
      { c: '洗发水', u: '沐浴露' },
      { c: '筷子', u: '刀叉' },
      { c: '铅笔', u: '圆珠笔' },
      { c: '橡皮', u: '涂改带' },
      { c: '剪刀', u: '指甲剪' },
      { c: '冰箱', u: '空调' },
      { c: '电视', u: '投影仪' },
      { c: '手机', u: 'iPad' },
      { c: '书包', u: '钱包' },
      { c: '跑鞋', u: '拖鞋' },
      { c: '围巾', u: '手套' },
      { c: '梳子', u: '镜子' },
      { c: '帽子', u: '头盔' },
      { c: '闹钟', u: '手表' },
      { c: '钥匙', u: '锁' },
      { c: '自行车', u: '滑板车' },
      { c: '地铁', u: '公交车' },
      { c: '飞机', u: '高铁' },
      { c: '葡萄', u: '提子' },
      { c: '麦当劳', u: '肯德基' },
      { c: '爆米花', u: '棉花糖' },
      { c: '芒果', u: '木瓜' },
      { c: '榴莲', u: '菠萝蜜' },
      { c: '猕猴桃', u: '奇异果' },
      { c: '橙子', u: '柚子' },
      { c: '麻辣烫', u: '关东煮' },
      { c: '汉堡包', u: '肉夹馍' },
      { c: '烧烤', u: '铁板烧' },
      { c: '寿司', u: '饭团' },
      { c: '泡泡糖', u: '口香糖' },
      { c: '充电宝', u: '充电器' },
      { c: '蓝牙耳机', u: '有线耳机' },
      { c: '拖鞋', u: '凉鞋' },
      { c: '鸭舌帽', u: '渔夫帽' },
      { c: '微信', u: 'QQ' },
      { c: '淘宝', u: '京东' },
      { c: '肥皂', u: '香皂' },
      { c: '洗洁精', u: '洗衣液' },
      { c: '热水袋', u: '暖宝宝' },
      { c: '窗帘', u: '百叶窗' },
      { c: '衣柜', u: '鞋柜' },
      { c: '浴巾', u: '毛巾' },
      { c: '洗衣机', u: '烘干机' },
      { c: '电磁炉', u: '微波炉' },
      { c: '榨汁机', u: '豆浆机' },
      { c: '保温杯', u: '玻璃杯' },
      { c: '地毯', u: '地垫' },
      { c: '沙发', u: '懒人豆袋' },
      { c: '帐篷', u: '睡袋' },
      { c: '牙膏', u: '洗面奶' },
      { c: '太阳镜', u: '护目镜' },
      { c: '围裙', u: '罩衣' },
      { c: '拖鞋', u: '棉拖鞋' },
      { c: '炒饭', u: '盖浇饭' },
      { c: '汤圆', u: '元宵' },
      { c: '粽子', u: '糍粑' },
      { c: '豆沙包', u: '莲蓉包' },
      { c: '橙汁', u: '柠檬水' },
      { c: '绿茶', u: '红茶' },
      { c: '瓜子', u: '花生' },
      { c: '话梅', u: '葡萄干' },
      { c: '煎饺', u: '锅贴' },
      { c: '白糖', u: '冰糖' }
    ]
  },

  // 2. 自然、动物与童趣常识 (85 组)
  nature_animals: {
    name: '🌿 自然动物常识',
    desc: '丰富孩子自然认知，生动可爱，激发想象力',
    pairs: [
      { c: '蝴蝶', u: '蜜蜂' },
      { c: '企鹅', u: '鸭子' },
      { c: '海豚', u: '海狮' },
      { c: '兔子', u: '仓鼠' },
      { c: '老虎', u: '狮子' },
      { c: '猫咪', u: '狗狗' },
      { c: '太阳', u: '月亮' },
      { c: '森林', u: '公园' },
      { c: '暴雨', u: '台风' },
      { c: '闪电', u: '打雷' },
      { c: '玫瑰', u: '向日葵' },
      { c: '恐龙', u: '鳄鱼' },
      { c: '熊猫', u: '考拉' },
      { c: '蜘蛛', u: '蚂蚁' },
      { c: '金鱼', u: '鲤鱼' },
      { c: '斑马', u: '长颈鹿' },
      { c: '鹦鹉', u: '八哥' },
      { c: '鸽子', u: '麻雀' },
      { c: '雪人', u: '冰雕' },
      { c: '彩虹', u: '晚霞' },
      { c: '泥土', u: '沙子' },
      { c: '爬山', u: '徒步' },
      { c: '游泳', u: '潜水' },
      { c: '露营', u: '野餐' },
      { c: '风筝', u: '气球' },
      { c: '仙人掌', u: '芦荟' },
      { c: '瀑布', u: '喷泉' },
      { c: '北极熊', u: '企鹅' },
      { c: '猴子', u: '猩猩' },
      { c: '蜗牛', u: '乌龟' },
      { c: '荷花', u: '睡莲' },
      { c: '星星', u: '萤火虫' },
      { c: '温泉', u: '泳池' },
      { c: '篝火', u: '火把' },
      { c: '晴天', u: '阴天' },
      { c: '猎豹', u: '金钱豹' },
      { c: '袋鼠', u: '考拉' },
      { c: '狐狸', u: '狼' },
      { c: '柴犬', u: '哈士奇' },
      { c: '变色龙', u: '壁虎' },
      { c: '乌龟', u: '甲鱼' },
      { c: '啄木鸟', u: '翠鸟' },
      { c: '喜鹊', u: '乌鸦' },
      { c: '孔雀', u: '火烈鸟' },
      { c: '蝙蝠', u: '燕子' },
      { c: '蜜蜂', u: '黄蜂' },
      { c: '蜻蜓', u: '豆娘' },
      { c: '蚕宝宝', u: '毛毛虫' },
      { c: '蜗牛', u: '蛞蝓' },
      { c: '螃蟹', u: '龙虾' },
      { c: '章鱼', u: '鱿鱼' },
      { c: '水母', u: '海葵' },
      { c: '珊瑚', u: '海草' },
      { c: '鲨鱼', u: '鲸鱼' },
      { c: '海龟', u: '陆龟' },
      { c: '骆驼', u: '羊驼' },
      { c: '刺猬', u: '豪猪' },
      { c: '松鼠', u: '花栗鼠' },
      { c: '仓鼠', u: '龙猫' },
      { c: '向日葵', u: '太阳花' },
      { c: '蒲公英', u: '柳絮' },
      { c: '枫叶', u: '银杏叶' },
      { c: '竹子', u: '芦苇' },
      { c: '蘑菇', u: '木耳' },
      { c: '灵芝', u: '人参' },
      { c: '沙漠', u: '戈壁' },
      { c: '绿洲', u: '海岛' },
      { c: '冰山', u: '雪山' },
      { c: '火山', u: '地热喷泉' },
      { c: '极光', u: '彩虹' },
      { c: '流星', u: '彗星' },
      { c: '日食', u: '月食' },
      { c: '大雾', u: '雾霾' },
      { c: '冰雹', u: '大雪' },
      { c: '龙卷风', u: '台风' },
      { c: '露水', u: '霜冻' },
      { c: '大白鹅', u: '填鸭' },
      { c: '大公鸡', u: '母鸡' },
      { c: '青蛙', u: '蟾蜍' },
      { c: '萤火虫', u: '小夜灯' },
      { c: '银河', u: '星座' },
      { c: '钟乳石', u: '石笋' },
      { c: '潮汐', u: '海浪' },
      { c: '森林', u: '丛林' },
      { c: '晨曦', u: '黄昏' }
    ]
  },

  // 3. 校园文体与学子共鸣 (65 组)
  school_sports: {
    name: '🏫 校园文体生活',
    desc: '文具课程、操场运动与童年游戏，Alex与全家专属共鸣',
    pairs: [
      { c: '钢笔', u: '圆珠笔' },
      { c: '铅笔盒', u: '笔袋' },
      { c: '橡皮擦', u: '涂改带' },
      { c: '直尺', u: '三角板' },
      { c: '圆规', u: '量角器' },
      { c: '字典', u: '词典' },
      { c: '课桌', u: '讲台' },
      { c: '黑板', u: '白板' },
      { c: '粉笔', u: '白板笔' },
      { c: '课间操', u: '眼保健操' },
      { c: '班长', u: '学习委员' },
      { c: '语文课', u: '英语课' },
      { c: '数学', u: '物理' },
      { c: '美术课', u: '手工课' },
      { c: '体育课', u: '活动课' },
      { c: '班会', u: '家长会' },
      { c: '作业本', u: '草稿纸' },
      { c: '红领巾', u: '校徽' },
      { c: '校服', u: '班服' },
      { c: '转笔刀', u: '削笔器' },
      { c: '荧光笔', u: '彩色笔' },
      { c: '订书机', u: '回形针' },
      { c: '固体胶', u: '双面胶' },
      { c: '剪刀', u: '美工刀' },
      { c: '乒乓球', u: '羽毛球' },
      { c: '网球', u: '壁球' },
      { c: '足球', u: '橄榄球' },
      { c: '篮球', u: '排球' },
      { c: '跳绳', u: '橡皮筋' },
      { c: '跑道', u: '足球场' },
      { c: '单杠', u: '双杠' },
      { c: '象棋', u: '围棋' },
      { c: '飞行棋', u: '斗兽棋' },
      { c: '扑克牌', u: 'UNO纸牌' },
      { c: '魔方', u: '乐高' },
      { c: '拼图', u: '积木' },
      { c: '盲盒', u: '扭蛋' },
      { c: '电子琴', u: '钢琴' },
      { c: '小提琴', u: '大提琴' },
      { c: '二胡', u: '琵琶' },
      { c: '架子鼓', u: '非洲鼓' },
      { c: '口琴', u: '竖笛' },
      { c: '水彩笔', u: '油画棒' },
      { c: '素描', u: '水彩画' },
      { c: '操场', u: '体育馆' },
      { c: '借书证', u: '学生证' },
      { c: '考卷', u: '练习册' },
      { c: '奖状', u: '奖杯' },
      { c: '升旗仪式', u: '开学典礼' },
      { c: '午休', u: '课间十分钟' },
      { c: '广播站', u: '电视台' },
      { c: '食堂', u: '小卖部' },
      { c: '科学实验室', u: '计算机教室' },
      { c: '运动会', u: '艺术节' },
      { c: '独轮车', u: '平衡车' },
      { c: '旱冰鞋', u: '滑板' },
      { c: '跳高', u: '跳远' },
      { c: '短跑', u: '接力跑' },
      { c: '仰卧起坐', u: '俯卧撑' },
      { c: '拔河', u: '接力赛' },
      { c: '班长', u: '组长' },
      { c: '暑假作业', u: '寒假作业' },
      { c: '课程表', u: '作息时间表' },
      { c: '校车', u: '公交车' },
      { c: '毕业照', u: '班级合影' }
    ]
  },

  // 4. 科技宇宙与奇趣幻想 (55 组)
  sci_tech_universe: {
    name: '🚀 科技宇宙奇趣',
    desc: '科学探索、人工智能、太空航天与脑洞幻想',
    pairs: [
      { c: '火箭', u: '航天飞机' },
      { c: '空间站', u: '人造卫星' },
      { c: '宇航员', u: '外星人' },
      { c: '机器人', u: '仿生人' },
      { c: '人工智能', u: '超级电脑' },
      { c: '无人机', u: '遥控飞机' },
      { c: '潜水艇', u: '航空母舰' },
      { c: '3D打印机', u: '激光雕刻机' },
      { c: 'VR眼镜', u: '3D立体眼镜' },
      { c: '平板电脑', u: '电纸书Kindle' },
      { c: '扫地机器人', u: '吸尘器' },
      { c: '洗碗机', u: '消毒柜' },
      { c: '太阳能板', u: '风力发电机' },
      { c: '天文望远镜', u: '显微镜' },
      { c: '水银温度计', u: '红外测温枪' },
      { c: '指南针', u: 'GPS卫星导航' },
      { c: '黑洞', u: '白矮星' },
      { c: '火星', u: '金星' },
      { c: '银河系', u: '仙女座星系' },
      { c: '宇宙飞船', u: '飞碟(UFO)' },
      { c: '遥控器', u: '游戏手柄' },
      { c: '智能音箱', u: '蓝牙音响' },
      { c: '智能手表', u: '运动手环' },
      { c: '无线路由器', u: '随身WiFi' },
      { c: '移动电源', u: '无线充电板' },
      { c: '家用投影仪', u: '激光电视' },
      { c: '电动汽车', u: '燃油汽车' },
      { c: '太阳能汽车', u: '磁悬浮列车' },
      { c: '纳米技术', u: '微米技术' },
      { c: '激光武器', u: '绝地光剑' },
      { c: '全息投影', u: '裸眼3D' },
      { c: '机械臂', u: '挖掘机' },
      { c: '火星探测车', u: '空间探测器' },
      { c: '月球背面', u: '火星表面' },
      { c: '太阳风暴', u: '地磁极光' },
      { c: '太空漫步', u: '失重漂浮' },
      { c: '时光机', u: '任意门' },
      { c: '隐形斗篷', u: '变色迷彩' },
      { c: '电脑芯片', u: '主板电路' },
      { c: '机械硬盘', u: '固态硬盘' },
      { c: '显示器', u: '触控屏' },
      { c: '机械键盘', u: '触控板' },
      { c: '鼠标', u: '轨迹球' },
      { c: '摄像头', u: '光线传感器' },
      { c: '卫星地图', u: '纸质地图' },
      { c: '气象气球', u: '探空火箭' },
      { c: '深海潜水器', u: '核潜艇' },
      { c: '空间折叠', u: '星际虫洞' },
      { c: '光速', u: '超音速' },
      { c: '超级英雄', u: '变种人' },
      { c: '钢铁战甲', u: '机动高达' },
      { c: '太空电梯', u: '重型运载火箭' },
      { c: '智慧城市', u: '智能家居' },
      { c: '太阳能翼', u: '锂电池板' },
      { c: '自动驾驶', u: '人工代驾' }
    ]
  },

  // 5. 趣味反差与经典角色 (60 组)
  humor_roles: {
    name: '🎭 趣味反差搞笑',
    desc: '经典综艺词对、影视童话与反差成语，充满欢声笑语',
    pairs: [
      { c: '孙悟空', u: '猪八戒' },
      { c: '班主任', u: '辅导员' },
      { c: '同学', u: '同桌' },
      { c: '保安', u: '保镖' },
      { c: '警察', u: '小偷' },
      { c: '奥特曼', u: '小怪兽' },
      { c: '情人节', u: '光棍节' },
      { c: '灰姑娘', u: '白雪公主' },
      { c: '爸爸', u: '妈妈' },
      { c: '哥哥', u: '弟弟' },
      { c: '鼠目寸光', u: '井底之蛙' },
      { c: '语无伦次', u: '词不达意' },
      { c: '喜羊羊', u: '灰太狼' },
      { c: '汤姆猫', u: '杰瑞鼠' },
      { c: '皇帝', u: '大臣' },
      { c: '超人', u: '蝙蝠侠' },
      { c: '举一反三', u: '触类旁通' },
      { c: '盲人摸象', u: '刻舟求剑' },
      { c: '零花钱', u: '压岁钱' },
      { c: '暑假作业', u: '寒假作业' },
      { c: '孙悟空', u: '六耳猕猴' },
      { c: '哪吒', u: '红孩儿' },
      { c: '猪八戒', u: '沙和尚' },
      { c: '熊大', u: '熊二' },
      { c: '光头强', u: '吉吉国王' },
      { c: '哆啦A梦', u: '大雄' },
      { c: '柯南', u: '怪盗基德' },
      { c: '钢铁侠', u: '蜘蛛侠' },
      { c: '绿巨人', u: '灭霸' },
      { c: '丑小鸭', u: '白天鹅' },
      { c: '匹诺曹', u: '阿里巴巴' },
      { c: '灰太狼', u: '红太狼' },
      { c: '懒羊羊', u: '沸羊羊' },
      { c: '皇帝的新装', u: '掩耳盗铃' },
      { c: '守株待兔', u: '亡羊补牢' },
      { c: '画蛇添足', u: '弄巧成拙' },
      { c: '狐假虎威', u: '狗仗人势' },
      { c: '对牛弹琴', u: '鸡同鸭讲' },
      { c: '顺手牵羊', u: '顺藤摸瓜' },
      { c: '亡羊补牢', u: '未雨绸缪' },
      { c: '东施效颦', u: '邯郸学步' },
      { c: '班主任', u: '教导主任' },
      { c: '校长', u: '园长' },
      { c: '舅舅', u: '叔叔' },
      { c: '姑姑', u: '阿姨' },
      { c: '闺蜜', u: '兄弟' },
      { c: '前桌', u: '后桌' },
      { c: '学霸', u: '学神' },
      { c: '星期六', u: '星期天' },
      { c: '早自习', u: '晚自习' },
      { c: '打喷嚏', u: '打哈欠' },
      { c: '眨眼睛', u: '翻白眼' },
      { c: '伸懒腰', u: '跺脚' },
      { c: '石头剪刀布', u: '抓阄' },
      { c: '捉迷藏', u: '老鹰抓小鸡' },
      { c: '萝卜蹲', u: '击鼓传花' },
      { c: '真心话', u: '大冒险' },
      { c: '睡懒觉', u: '熬夜' },
      { c: '减肥', u: '节食' },
      { c: '拆快递', u: '拆盲盒' }
    ]
  },

  // 6. 少儿双语口语实战库 (85 组)
  bilingual_esl: {
    name: '🇬🇧 少儿双语口语',
    desc: '中英双语标注，附带地道英语句式提示，边玩边练口语描述',
    isBilingual: true,
    pairs: [
      { c: 'Cat (猫咪)', u: 'Dog (狗狗)', hint: 'It has four legs and soft fur, very popular household pet...' },
      { c: 'Apple (苹果)', u: 'Tomato (番茄)', hint: 'It is round and red, sweet or juicy, you can eat it fresh...' },
      { c: 'Bicycle (自行车)', u: 'Motorcycle (摩托车)', hint: 'It has two wheels on the road, people ride it to travel...' },
      { c: 'Sun (太阳)', u: 'Moon (月亮)', hint: 'It shines in the sky and brings light to our world...' },
      { c: 'Car (小轿车)', u: 'Bus (公交车)', hint: 'People ride inside it on the road with engine and seats...' },
      { c: 'Book (书本)', u: 'Notebook (笔记本)', hint: 'It has pages made of paper to read stories or write...' },
      { c: 'Rabbit (小兔子)', u: 'Hamster (小仓鼠)', hint: 'A cute small pet with soft ears and fur, loves carrots or seeds...' },
      { c: 'Pizza (披萨)', u: 'Hamburger (汉堡包)', hint: 'Delicious fast food enjoyed with cheese, bread or meat...' },
      { c: 'Sea (大海)', u: 'Swimming Pool (游泳池)', hint: 'A big place full of water where you can swim and splash...' },
      { c: 'Lion (狮子)', u: 'Tiger (老虎)', hint: 'A brave wild animal king in the forest or jungle...' },
      { c: 'Milk (牛奶)', u: 'Soy Milk (豆浆)', hint: 'A healthy white drink often enjoyed for breakfast...' },
      { c: 'Ice Cream (冰淇淋)', u: 'Cake (甜蛋糕)', hint: 'A sweet dessert eaten at birthday parties or sunny summer...' },
      { c: 'Hat (圆顶帽)', u: 'Cap (鸭舌帽)', hint: 'You wear it on your head when going outside under the sun...' },
      { c: 'Pen (钢笔)', u: 'Pencil (铅笔)', hint: 'You hold it in your fingers to write homework or draw...' },
      { c: 'Bread (面包)', u: 'Cookie (曲奇饼干)', hint: 'Baked snack made from flour, good for breakfast or tea...' },
      { c: 'Tree (大树)', u: 'Flower (花朵)', hint: 'Growing in soil with green leaves, plants in nature...' },
      { c: 'Fish (游鱼)', u: 'Bird (小鸟)', hint: 'An animal that moves freely in nature, swimming or flying...' },
      { c: 'Train (火车)', u: 'Subway (地铁)', hint: 'A long vehicle running on metal tracks carrying passengers...' },
      { c: 'Doctor (医生)', u: 'Nurse (护士)', hint: 'A kind person working in a hospital to help patients get well...' },
      { c: 'Teacher (老师)', u: 'Student (学生)', hint: 'Someone you meet every weekday inside school classrooms...' },
      { c: 'Clock (大挂钟)', u: 'Watch (手表)', hint: 'It tells you the exact time of day with numbers and hands...' },
      { c: 'Guitar (木吉他)', u: 'Piano (大钢琴)', hint: 'A musical instrument that plays beautiful melodies and songs...' },
      { c: 'Shirt (长袖衬衫)', u: 'T-shirt (短袖T恤)', hint: 'Clothes you wear on your upper body every single day...' },
      { c: 'Rain (下雨)', u: 'Snow (下雪)', hint: 'Water or frozen crystals falling from clouds above...' },
      { c: 'Football (足球)', u: 'Basketball (篮球)', hint: 'A popular ball sport played with teammates on a court...' },
      { c: 'Summer (夏天)', u: 'Winter (冬天)', hint: 'A season of the year with very special weather and temperatures...' },
      { c: 'Bed (大床)', u: 'Sofa (沙发)', hint: 'Comfortable soft furniture where you lie down or sit to rest...' },
      { c: 'King (国王)', u: 'Queen (王后)', hint: 'A noble royal leader wearing a golden crown in a palace...' },
      { c: 'Mountain (高山)', u: 'Hill (小山丘)', hint: 'High natural ground rising high above the surrounding land...' },
      { c: 'River (河流)', u: 'Lake (湖泊)', hint: 'Calm or flowing natural freshwater found across the Earth...' },
      { c: 'Shoes (运动鞋)', u: 'Socks (棉袜子)', hint: 'Things you wear on your feet before walking or running outside...' },
      { c: 'Cup (水杯)', u: 'Bowl (瓷碗)', hint: 'An everyday dish used during breakfast, lunch or dinner...' },
      { c: 'Elephant (大象)', u: 'Giraffe (长颈鹿)', hint: 'A huge impressive wild animal you can see at the safari zoo...' },
      { c: 'Star (星星)', u: 'Diamond (钻石)', hint: 'Sparkling and shining bright like little glittering lights...' },
      { c: 'Door (大门)', u: 'Window (窗户)', hint: 'A part of a room that can be opened to enter or see outside...' },
      { c: 'Chair (椅子)', u: 'Bench (长椅)', hint: 'A piece of furniture designed for people to sit on comfortably...' },
      { c: 'Blanket (毛毯)', u: 'Pillow (枕头)', hint: 'Soft cozy bedding used at night when sleeping warm...' },
      { c: 'Mirror (镜子)', u: 'Photo (照片)', hint: 'It shows your face and appearance clearly when you look...' },
      { c: 'Soap (肥皂)', u: 'Shampoo (洗发水)', hint: 'Used with warm water to wash away dirt and stay clean...' },
      { c: 'Toothbrush (牙刷)', u: 'Toothpaste (牙膏)', hint: 'Tools used in the bathroom morning and night for healthy teeth...' },
      { c: 'School (学校)', u: 'Library (图书馆)', hint: 'A quiet or lively place full of books, knowledge and students...' },
      { c: 'Hospital (医院)', u: 'Clinic (诊所)', hint: 'A medical place where doctors care for sick or injured people...' },
      { c: 'Park (公园)', u: 'Zoo (动物园)', hint: 'A wonderful outdoor place to visit on sunny weekends with family...' },
      { c: 'Cinema (电影院)', u: 'Theater (剧院)', hint: 'A dark hall with a giant screen where you watch exciting shows...' },
      { c: 'Supermarket (超市)', u: 'Bakery (面包店)', hint: 'A busy store where you pick items and pay at the counter...' },
      { c: 'Airport (机场)', u: 'Railway Station (火车站)', hint: 'A big transportation hub where travelers depart on journeys...' },
      { c: 'Kitchen (厨房)', u: 'Dining Room (餐厅)', hint: 'A room in the house where delicious meals are prepared or eaten...' },
      { c: 'Bedroom (卧室)', u: 'Living Room (客厅)', hint: 'A cozy room in your home where family gathers or sleeps...' },
      { c: 'Bathroom (卫生间)', u: 'Balcony (阳台)', hint: 'A special area in your home with tiles, water, or fresh air...' },
      { c: 'Candle (蜡烛)', u: 'Flashlight (手电筒)', hint: 'It gives off light in the dark when electricity is off...' },
      { c: 'Key (钥匙)', u: 'Lock (挂锁)', hint: 'A metal item used to secure doors and protect your home...' },
      { c: 'Scissors (剪刀)', u: 'Knife (小刀)', hint: 'A sharp metal tool used to cut paper, fabric or food carefully...' },
      { c: 'Fork (叉子)', u: 'Spoon (勺子)', hint: 'Tableware held in hands to eat soup, pasta, or rice...' },
      { c: 'Backpack (双肩包)', u: 'Handbag (手提包)', hint: 'A bag used to carry books, water bottles and belongings...' },
      { c: 'Balloon (气球)', u: 'Kite (风筝)', hint: 'Light and colorful object that can float or fly up into the air...' },
      { c: 'Fire (火焰)', u: 'Light (灯光)', hint: 'It glows bright and warm, illuminating the surrounding darkness...' },
      { c: 'Gold (黄金)', u: 'Silver (白银)', hint: 'Precious shiny metal used for coins, jewelry and medals...' },
      { c: 'Island (海岛)', u: 'Beach (沙滩)', hint: 'A sunny vacation place surrounded by blue ocean waves...' },
      { c: 'Desert (沙漠)', u: 'Forest (森林)', hint: 'A vast natural landscape with unique plants and climate...' },
      { c: 'Volcano (火山)', u: 'Earthquake (地震)', hint: 'A powerful and dramatic force of nature from deep underground...' },
      { c: 'Rainbow (彩虹)', u: 'Sunset (日落)', hint: 'A beautiful colorful view appearing in the sky after rain or evening...' },
      { c: 'Cloud (白云)', u: 'Fog (大雾)', hint: 'Soft white or grey water vapor floating in the atmosphere...' },
      { c: 'Tennis (网球)', u: 'Badminton (羽毛球)', hint: 'A racket sport where players hit a ball or shuttlecock over a net...' },
      { c: 'Spring (春天)', u: 'Autumn (秋天)', hint: 'A lovely pleasant season with blooming flowers or falling leaves...' },
      { c: 'Hippo (河马)', u: 'Rhino (犀牛)', hint: 'A giant heavy African mammal with thick skin and round body...' },
      { c: 'Horse (马)', u: 'Donkey (驴子)', hint: 'A strong domestic animal with four hooves that can carry riders...' },
      { c: 'Monkey (猴子)', u: 'Gorilla (大猩猩)', hint: 'An intelligent primate that climbs trees and lives in troops...' },
      { c: 'Dolphin (海豚)', u: 'Whale (鲸鱼)', hint: 'A smart friendly mammal swimming and jumping in ocean waves...' },
      { c: 'Shark (鲨鱼)', u: 'Crocodile (鳄鱼)', hint: 'A fierce predator with sharp teeth living in water...' },
      { c: 'Eagle (老鹰)', u: 'Owl (猫头鹰)', hint: 'A sharp-eyed bird of prey with strong talons and wings...' },
      { c: 'Duck (鸭子)', u: 'Swan (天鹅)', hint: 'A waterfowl with webbed feet paddling gracefully on lakes...' },
      { c: 'Snake (蛇)', u: 'Lizard (蜥蜴)', hint: 'A scaly reptile that glides silently or sunbathes on rocks...' },
      { c: 'Frog (青蛙)', u: 'Toad (蟾蜍)', hint: 'An amphibian that hops near ponds and catches insects with tongue...' },
      { c: 'Airplane (飞机)', u: 'Helicopter (直升机)', hint: 'An aircraft with wings or spinning propellers soaring through clouds...' },
      { c: 'Ship (大轮船)', u: 'Submarine (潜水艇)', hint: 'A massive vessel navigating across or deep under ocean waters...' },
      { c: 'Rocket (火箭)', u: 'UFO (飞碟)', hint: 'A spacecraft blasting off from Earth toward the stars and universe...' },
      { c: 'Robot (机器人)', u: 'Alien (外星人)', hint: 'A futuristic or mysterious figure from science fiction stories...' },
      { c: 'Computer (电脑)', u: 'Tablet (平板iPad)', hint: 'An electronic digital screen device for study, work and gaming...' },
      { c: 'Camera (数码相机)', u: 'Smartphone (智能手机)', hint: 'A gadget you use to take high-resolution photos and videos...' },
      { c: 'Glasses (近视眼镜)', u: 'Sunglasses (太阳镜)', hint: 'Eyewear with two lenses worn on the face to protect or sharpen vision...' },
      { c: 'Umbrella (雨伞)', u: 'Raincoat (雨衣)', hint: 'Waterproof gear that keeps you dry during rainy days outdoors...' },
      { c: 'Juice (果汁)', u: 'Soda (汽水)', hint: 'A refreshing cold beverage sweet and tasty to drink with ice...' },
      { c: 'Tea (热茶)', u: 'Coffee (热咖啡)', hint: 'A hot aromatic morning beverage brewed with leaves or roasted beans...' },
      { c: 'Prince (王子)', u: 'Princess (公主)', hint: 'A royal son or daughter in fairy tales living in castles...' },
      { c: 'Watermelon (西瓜)', u: 'Melon (甜瓜)', hint: 'A large sweet juicy summer fruit with lots of water...' }
    ]
  }
};

// 计算总词库统计
function getUndercoverStats() {
  let total = 0;
  const categories = [];
  for (const [key, pool] of Object.entries(UNDERCOVER_WORD_POOLS)) {
    total += pool.pairs.length;
    categories.push({ key, name: pool.name, count: pool.pairs.length });
  }
  return { total, categories };
}

// 导出或挂载至全局
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { UNDERCOVER_WORD_POOLS, getUndercoverStats };
} else if (typeof window !== 'undefined') {
  window.UNDERCOVER_WORD_POOLS = UNDERCOVER_WORD_POOLS;
  window.getUndercoverStats = getUndercoverStats;
}
